CREATE TABLE IF NOT EXISTS urls (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS url_checks (
    id SERIAL PRIMARY KEY,
    url_id INT REFERENCES urls(id) ON DELETE CASCADE,
    status_code INT,
    h1 VARCHAR(255),
    title VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE urls ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE url_checks ADD COLUMN IF NOT EXISTS status_code INT;
ALTER TABLE url_checks ADD COLUMN IF NOT EXISTS h1 VARCHAR(255);
ALTER TABLE url_checks ADD COLUMN IF NOT EXISTS title VARCHAR(255);
ALTER TABLE url_checks ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE url_checks ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
